### ISSUE TITLE
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'

### ISSUE THREAD

**Issue by phosseini** [aio-libs/aioredis-py#1082]
I'm using Ray for hyperparameter tuning on Google Colab, everything was fine until the last time that I re-installed Ray. I'm getting the following error:

```
2021-07-30 19:41:49,014	ERROR services.py:1254 -- Failed to start the dashboard: Failed to start the dashboard, return code 1. The last 10 lines of /tmp/ray/session_2021-07-30_19-41-47_222866_75/logs/dashboard.log:
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/dashboard.py", line 118, in run
    await self.dashboard_head.run()
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/head.py", line 64, in run
    dashboard_consts.RETRY_REDIS_CONNECTION_TIMES)
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
    return await aioredis.create_redis_pool(
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
2021-07-30 19:41:52,007	WARNING worker.py:1189 -- The agent on node 01151c700d47 failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 354, in <module>
    loop.run_until_complete(agent.run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 130, in run
    dashboard_consts.RETRY_REDIS_CONNECTION_TIMES)
  File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
    return await aioredis.create_redis_pool(
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
```

I wonder if this error is related to `aioredis` or Ray?

**Comment by seandstewart** [comment]
Hey @phosseini -

We just released v2.0 of aioredis, which has a completely new high-level client api mirroring the synchronous `redis-py`. Until Ray updates their library to support v2, I'd recommend pinning your aioredis dependency to <2.0.

**Comment by phosseini** [comment]
> Hey @phosseini -
> 
> We just released v2.0 of aioredis, which has a completely new high-level client api mirroring the synchronous `redis-py`. Until Ray updates their library to support v2, I'd recommend pinning your aioredis dependency to <2.0.

I see, thanks. I just downgraded to v1.3.1 for now which I think is the most recent version before v2.0?

**Comment by Andrew-Chen-Wang** [comment]
Yes @phosseini Note we will not be doing any security updates to major version 1. I'd recommend you install the beta version 2.0.0b1; we're super close to the full release to 2.0.0.

**Comment by abrookins** [comment]
Looks like this was related to version change, so I'm closing for now. Reopen if I'm mistaken!
