### ISSUE TITLE
Bug on multi_get with aioredis 2.0.0

### ISSUE THREAD

**Issue by danieldaeschle** [aio-libs/aioredis-py#1143]
### Describe the bug

It crashes when using multi_get with aioredis backend.

### To Reproduce

1. Use redis as backend.
2. Do a multi_get on it

### Expected behavior

It should work.

### Logs/tracebacks

```python-traceback
This happens:

Traceback (most recent call last):
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\fastapi\routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\fastapi\routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\dd\Projects\wordembeddingservice\.\word_embedding\api.py", line 57, in vectors
    return await lm.get_vectors(words_split, True if keep_order else False)
  File "C:\Users\dd\Projects\wordembeddingservice\.\word_embedding\language_model.py", line 90, in get_vectors
    token_values = await self.cache_mget(found_tokens)
  File "C:\Users\dd\Projects\wordembeddingservice\.\word_embedding\language_model.py", line 77, in cache_mget
    values = await self.cache.multi_get(keys)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\aiocache\base.py", line 61, in _enabled
    return await func(*args, **kwargs)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\aiocache\base.py", line 45, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
  File "C:\Users\dd\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 494, in wait_for
    return fut.result()
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\aiocache\base.py", line 75, in _plugins
    ret = await func(self, *args, **kwargs)
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\aiocache\base.py", line 222, in multi_get
    for value in await self._multi_get(
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\aiocache\backends\redis.py", line 19, in wrapper
    pool = await self._get_pool()
  File "c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages\aiocache\backends\redis.py", line 219, in _get_pool
    self._pool = await aioredis.create_pool((self.endpoint, self.port), **kwargs)
AttributeError: module 'aioredis' has no attribute 'create_pool'
```

### Python Version

```console
Python 3.8.10
```

### aioredis Version

```console
Name: aioredis
Version: 2.0.0
Summary: asyncio (PEP 3156) Redis support
Home-page: https://github.com/aio-libs/aioredis
Author: None
Author-email: None
License: MIT
Location: c:\users\dd\projects\wordembeddingservice\venv\lib\site-packages
Requires: typing-extensions, async-timeout
Required-by:
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by seandstewart** [comment]
Hey @danieldaeschle - 

It looks like this is actually a bug with how `aiocache` is instantiating an `aioredis` client. `aioredis.create_redis` was deprecated with v2.0.

I'd recommend opening an issue with that library.
