### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)

### ISSUE THREAD

**Issue by Jacks349** [aio-libs/aioredis-py#1180]
### Describe the bug

Hello, i'm using of Aioredis (version 2.0) to connect to a Redis DigitalOcean db, the problem is that i keep getting the following error: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)`
I don't understand if the problem is with DigitalOcean or with Aioredis.

### To Reproduce

I'm using Windows 10, here is my code:

```
import asyncio

import async_timeout

import aioredis

async def reader(channel: aioredis.client.PubSub):
    while True:
        try:
            async with async_timeout.timeout(1):
                message = await channel.get_message(ignore_subscribe_messages=True)
                if message is not None:
                    print(f"(Reader) Message Received: {message}")
                    if message["data"] == STOPWORD:
                        print("(Reader) STOP")
                        break
                await asyncio.sleep(0.01)
        except asyncio.TimeoutError:
            pass

async def main():
    redis = aioredis.from_url("rediss://<MY-USER>:<MY-PASS>@<REDIS-DB>.b.db.ondigitalocean.com:25061")
    pubsub = redis.pubsub()
    await pubsub.subscribe("test")

    asyncio.create_task(reader(pubsub))


asyncio.run(main())
```

### Expected behavior

This code should connect to my DigitalOcean db and receive messages from a pubsub channel.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\aioredis\connection.py", line 650, in connect
    await self._connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\aioredis\connection.py", line 677, in _connect
    reader, writer = await asyncio.open_connection(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)
```

### Python Version

```console
$ python --version
Python 3.8.3
```

### aioredis Version

```console
$ python -m pip show aioredis
Name: aioredis
Version: 2.0.0
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by seandstewart** [comment]
@Jacks349 -

This is likely an issue with the SSL certificate that you're using to connect to your DigitalOcean deployment. You may need to regenerate your certificate. If that's not an option, then you'll need to reach out to DigitalOcean support.
