### ISSUE TITLE
Can't pass multiple arguments to `hset(..., mappint={...})`

### ISSUE THREAD

**Issue by nxtlo** [aio-libs/aioredis-py#1261]
### Describe the bug

Passing multiple arguments to the mapping in `Redis.hset(mapping={...})` raises `ResponseError`.

### To Reproduce

Working example.
```py
import asyncio
import aioredis

async def main() -> None:
    redis = aioredis.Redis(decode_responses=True)
    # Only 1 key -> value
    await redis.hset("users", mapping={"me": 'user1'})
    print(await redis.hgetall("users"))
    # Returns {'me': 'user1'}
    await redis.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Example where the bug occurs

```py
import asyncio
import aioredis

async def main() -> None:
    redis = aioredis.Redis(decode_responses=True)
    # Passing multiple key -> value to the mapping raises the error below.
    await redis.hset("users", mapping={"me": 'user1', "me2": "user2"})
    print(await redis.hgetall("users"))
    await redis.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

### Expected behavior

The bugged example is supposed to return a mapping with the 2 inserted keys which's `{"me": "user1", "me2": "user2"}`
but raises `ResponseError` instead.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "auth_test\t.py", line 12, in <module>
    loop.run_until_complete(main())
  File "Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "auth_test\t.py", line 7, in main
    await redis.hset("users", mapping={"me": 'user1', "me2": "user2"})
  File "auth_test\.venv\lib\site-packages\aioredis\client.py", line 1085, in execute_command
    return await self.parse_response(conn, command_name, **options)
  File "auth_test\.venv\lib\site-packages\aioredis\client.py", line 1101, in parse_response
    response = await connection.read_response()
  File "auth_test\.venv\lib\site-packages\aioredis\connection.py", line 919, in read_response
    raise response from None
aioredis.exceptions.ResponseError: wrong number of arguments for 'hset' command
```

### Python Version

```console
$ python --version
Python 3.10.1
```

### aioredis Version

```console
$ python -m pip show aioredis
Name: aioredis
Version: 2.0.1
Summary: asyncio (PEP 3156) Redis support
Home-page: https://github.com/aio-libs/aioredis-py     
Author:
Author-email:
License: MIT
Location: \auth_test\.venv\lib\site-packages
Requires: typing-extensions, async-timeout
Required-by:
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Andrew-Chen-Wang** [comment]
Apologies. Is this resolved in #1156?

**Comment by nxtlo** [comment]
No not really. I just installed aioredis from that branch and it still raises the same error.

```py
  File "D:\Projects\auth_test\t.py", line 6, in main
    await r.hset("users", mapping={"me": "user1", "me2": "user2"})
  File "D:\Projects\auth_test\.venv\lib\site-packages\aioredis\client.py", line 1173, in execute_command
    return await conn.retry.call_with_retry(
  File "D:\Projects\auth_test\.venv\lib\site-packages\aioredis\retry.py", line 52, in call_with_retry
    return await do()
  File "D:\Projects\auth_test\.venv\lib\site-packages\aioredis\client.py", line 1152, in _send_command_parse_response  
    return await self.parse_response(conn, command_name, **options)
  File "D:\Projects\auth_test\.venv\lib\site-packages\aioredis\client.py", line 1188, in parse_response
    response = await connection.read_response()
  File "D:\Projects\auth_test\.venv\lib\site-packages\aioredis\connection.py", line 912, in read_response
    raise response from None
aioredis.exceptions.ResponseError: wrong number of arguments for 'hset' command
```

**Comment by Andrew-Chen-Wang** [comment]
I'm not really sure what to say since I can't reproduce this. If you find a solution, please let me know:

```python
In [8]: async def main():
   ...:     redis = aioredis.Redis(decode_responses=True)
   ...:     try:
   ...:         await redis.hset("users", mapping={"me": "user1", "me2": "user2"})
   ...:         print(1, await redis.hgetall("users"))
   ...:     except Exception as e:
   ...:         print(2, e)
   ...:     finally:
   ...:         await redis.close()
   ...: 
In [9]: await main()
1 {'me': 'user1', 'me2': 'user2'}

```

**Comment by nxtlo** [comment]
I figured out that the the issue was in my end, I was using Redis on windows version `v=3.2.100` which's pretty a outdated build. 
re-tested it on linux distro and worked fine. Will close this for now. Thanks!
