### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by blueyed** [aio-libs/aioredis-py#521]
It looks like there are some flaky tests (on CI at least).

I am creating this issue to track them.

Via https://ci.appveyor.com/project/popravich/aioredis/builds/21750614/job/pdq7rc2ncf2kspdj (https://github.com/aio-libs/aioredis/pull/520):
```
================================== FAILURES ===================================
_______________ test_operations[redis_v3.0.503-blocking_pop-10] _______________
pool_or_redis = <function pool_or_redis.<locals>.redis_factory at 0x000000CD1540FE18>
test_case = <function blocking_pop at 0x000000CD13CA9510>, pool_size = 10
loop = <_WindowsSelectorEventLoop running=False closed=False debug=True>
    @pytest.mark.run_loop
    @pytest.mark.parametrize('test_case,pool_size', [
        (simple_get_set, 1),
        (pipeline, 1),
        (transaction, 1),
        pytest.param(
            blocking_pop, 1,
            marks=pytest.mark.xfail(
                reason="blpop gets connection first and blocks")
            ),
        (simple_get_set, 10),
        (pipeline, 10),
        (transaction, 10),
        (blocking_pop, 10),
    ], ids=lambda o: getattr(o, '__name__', repr(o)))
    async def test_operations(pool_or_redis, test_case, pool_size, loop):
        repeat = 100
        redis = await pool_or_redis(pool_size)
        done, pending = await asyncio.wait(
            [asyncio.ensure_future(test_case(redis, i, loop), loop=loop)
             for i in range(repeat)], loop=loop)
    
        assert not pending
        success = 0
        failures = []
        for fut in done:
            exc = fut.exception()
            if exc is None:
                success += 1
            else:
                failures.append(exc)
>       assert repeat == success, failures
E       AssertionError: [AssertionError("None
E         assert None == ['list-key', 'val']",), AssertionError("None
E         assert None == ['list-key', 'val']",)]
E       assert 100 == 98
tests\integration_test.py:99: AssertionError
------------------------------ Captured log call ------------------------------
base_events.py            1421 WARNING  Executing <Task pending coro=<_wait_coro() running at C:\projects\aioredis\tests\conftest.py:553> wait_for=<Future pending cb=[Task._wakeup()] created at C:\Python35-x64\lib\asyncio\base_events.py:275> cb=[_run_until_complete_cb() at C:\Python35-x64\lib\asyncio\base_events.py:176] created at C:\Python35-x64\lib\asyncio\base_events.py:446> took 0.172 seconds
```

**Comment by blueyed** [comment]
```
python3 examples/pubsub2.py
message in b'channel:1': Hello
message in b'channel:2': Hello
message in b'channel:1': ,
message in b'channel:2': ,
message in b'channel:1': world!
message in b'channel:2': world!
Traceback (most recent call last):
  File "examples/pubsub2.py", line 56, in <module>
    loop.run_until_complete(pubsub())
  File "/opt/python/3.6.7/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "examples/pubsub2.py", line 49, in pubsub
    await asyncio.gather(tsk1, tsk2)
  File "examples/pubsub2.py", line 25, in async_reader2
    msg = await channel.get(encoding='utf-8')
  File "/home/travis/build/aio-libs/aioredis/aioredis/pubsub.py", line 67, in get
    raise ChannelClosedError()
aioredis.errors.ChannelClosedError
Makefile:73: recipe for target 'examples/pubsub2.py' failed
make: *** [examples/pubsub2.py] Error 1
```
(https://travis-ci.com/aio-libs/aioredis/jobs/172383672)
